name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: |
        npx cross-env TOKEN="${{ secrets.TOKEN }}" NODE_ENV="production" npm test

    - name: Upload Jest Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: jest-test-report
        path: |
          test-reports/test-report.html
          test-reports/jest-test-report.xml
          
